server:
  port: 9002

spring:
  application:
    name: cloud-nacos-payment
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.10:8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
