server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.5:8081
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: tx_service_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3305/seata_order?verifyServerCertificate=false&useSSL=true
    username: root
    password: 123456
    
feign:
  hystrix:
    enabled: false
    
mybatis:
  mapperLocations: classpath:mapper/*.xml
