server:
  port: 84

spring:
  application:
    name: cloud-nacos-sentinel-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.5:8081   #nginx nacos 集群地址
    sentinel:
      transport:
        #配置sentinel dashboard 地址
        dashboard: localhost:8080
        #默认端口，假如被占用会自动从8719开始依次扫描，直到端口没有被占用
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.1.5:8081
            dataId: cloud-nacos-sentinel-consumer
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow


management:
  endpoints:
    web:
      exposure:
        include: '*'

#激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true